# pyright: strict
"""forge-mvc-mfa — Module MFA pour Forge : TOTP, codes de recuperation, anti-replay, rate-limit.

Opt-in officiel Forge distribue separement depuis Forge 2.4.0.
Voir packages/forge-mvc-mfa/README.md pour la documentation.
"""
from forge_mvc_mfa.secret_crypto import (
    MfaSecretInvalidKey,
    MfaSecretKeyMissing,
    MfaSecretKeyPlaceholder,
    MfaSecretNotEncrypted,
    decrypt_totp_secret,
    encrypt_totp_secret,
    validate_mfa_secret_key_config,
)
from forge_mvc_mfa.mfa import (
    MFA_CHALLENGE_STARTED_AT_KEY,
    MFA_CHALLENGE_USER_ID_KEY,
    MFA_CHALLENGE_MAX_ATTEMPTS,
    MFA_CHALLENGE_WINDOW_SECONDS,
    MFA_FACTOR_RECOVERY,
    MFA_FACTOR_TOTP,
    MFA_REVALIDATION_AT_KEY,
    MFA_REVALIDATION_USER_ID_KEY,
    MFA_REVALIDATION_MAX_ATTEMPTS,
    MFA_REVALIDATION_WINDOW_SECONDS,
    MFA_STATUS_ACTIVE,
    MFA_STATUS_DISABLED,
    MFA_STATUS_PENDING,
    AuthMfaFactor,
    MfaChallengeResult,
    MfaRevalidationResult,
    TotpSetup,
    clear_mfa_challenge,
    clear_mfa_revalidation,
    confirm_totp_factor,
    create_totp_factor,
    generate_totp_secret,
    get_mfa_challenge_user_id,
    get_mfa_revalidated_user_id,
    has_pending_mfa_challenge,
    has_recent_mfa_revalidation,
    is_mfa_enabled,
    is_mfa_factor_active,
    is_valid_mfa_factor,
    mark_mfa_revalidated,
    normalize_mfa_factor,
    require_recent_mfa,
    start_mfa_challenge,
    totp_provisioning_uri,
    validate_mfa_factor_contract,
    verify_mfa_challenge,
    verify_mfa_revalidation,
    verify_totp_code,
)
from forge_mvc_mfa.recovery import (
    AuthMfaRecoveryCode,
    RecoveryCodesSetup,
    consume_recovery_code,
    create_recovery_codes,
    generate_recovery_code,
    hash_recovery_code,
    is_valid_recovery_code_record,
    normalize_recovery_code,
    normalize_recovery_code_record,
    validate_recovery_code_contract,
    verify_recovery_code,
)
from forge_mvc_mfa.totp_replay import (
    InMemoryTotpReplayStore,
    TotpReplayStore,
    check_and_record,
    get_replay_store,
    is_replay,
    purge_all as purge_all_totp_replay,
    purge_old,
    record_used,
    reset_replay_store,
    set_replay_store,
    step_for_time,
)

__version__ = "1.0.0rc5"

__all__ = [
    # mfa — facteurs et types
    "AuthMfaFactor",
    "MfaChallengeResult",
    "MfaRevalidationResult",
    "TotpSetup",
    "MFA_FACTOR_TOTP",
    "MFA_FACTOR_RECOVERY",
    "MFA_STATUS_PENDING",
    "MFA_STATUS_ACTIVE",
    "MFA_STATUS_DISABLED",
    # mfa — clés de session
    "MFA_CHALLENGE_USER_ID_KEY",
    "MFA_CHALLENGE_STARTED_AT_KEY",
    "MFA_CHALLENGE_MAX_ATTEMPTS",
    "MFA_CHALLENGE_WINDOW_SECONDS",
    "MFA_REVALIDATION_USER_ID_KEY",
    "MFA_REVALIDATION_AT_KEY",
    "MFA_REVALIDATION_MAX_ATTEMPTS",
    "MFA_REVALIDATION_WINDOW_SECONDS",
    # mfa — TOTP
    "create_totp_factor",
    "confirm_totp_factor",
    "verify_totp_code",
    "totp_provisioning_uri",
    "generate_totp_secret",
    "validate_mfa_factor_contract",
    "normalize_mfa_factor",
    "is_valid_mfa_factor",
    "is_mfa_factor_active",
    "is_mfa_enabled",
    # mfa — challenge
    "start_mfa_challenge",
    "has_pending_mfa_challenge",
    "get_mfa_challenge_user_id",
    "clear_mfa_challenge",
    "verify_mfa_challenge",
    # mfa — revalidation
    "mark_mfa_revalidated",
    "has_recent_mfa_revalidation",
    "get_mfa_revalidated_user_id",
    "clear_mfa_revalidation",
    "verify_mfa_revalidation",
    "require_recent_mfa",
    # recovery
    "AuthMfaRecoveryCode",
    "RecoveryCodesSetup",
    "generate_recovery_code",
    "normalize_recovery_code",
    "hash_recovery_code",
    "verify_recovery_code",
    "create_recovery_codes",
    "consume_recovery_code",
    "validate_recovery_code_contract",
    "normalize_recovery_code_record",
    "is_valid_recovery_code_record",
    # secret_crypto
    "encrypt_totp_secret",
    "decrypt_totp_secret",
    "validate_mfa_secret_key_config",
    "MfaSecretKeyMissing",
    "MfaSecretInvalidKey",
    "MfaSecretKeyPlaceholder",
    "MfaSecretNotEncrypted",
    # totp_replay
    "is_replay",
    "record_used",
    "check_and_record",
    "purge_old",
    "purge_all_totp_replay",
    "step_for_time",
    # totp_replay — magasin enfichable (MFA-TOTP-REPLAY-SHARED-001)
    "TotpReplayStore",
    "InMemoryTotpReplayStore",
    "set_replay_store",
    "get_replay_store",
    "reset_replay_store",
]
