# pyright: strict
"""Codes d'erreur stables pour forge entity:validate.

Ces codes préfixés FORGE_ sont stables et servent de base pour :
- la sortie humaine de forge entity:validate ;
- les tests ciblés ;
- la future sortie --json (ENTITY-CONTRACT-010) ;
- la documentation et les traductions éventuelles.

Convention :
- FORGE_ENTITY_*   — erreurs liées aux fichiers d'entité ;
- FORGE_RELATION_* — erreurs liées aux relations ;
- FORGE_PIVOT_*    — erreurs liées aux tables pivot.
"""

from __future__ import annotations

# ── Erreurs d'entité ──────────────────────────────────────────────────────────

FORGE_ENTITY_JSON_INVALID = "FORGE_ENTITY_JSON_INVALID"
FORGE_ENTITY_SCHEMA_MISSING = "FORGE_ENTITY_SCHEMA_MISSING"
FORGE_ENTITY_SCHEMA_INVALID = "FORGE_ENTITY_SCHEMA_INVALID"
FORGE_ENTITY_DUPLICATE_FIELD = "FORGE_ENTITY_DUPLICATE_FIELD"
FORGE_ENTITY_RESERVED_PYTHON_NAME = "FORGE_ENTITY_RESERVED_PYTHON_NAME"
FORGE_ENTITY_DUPLICATE_TABLE = "FORGE_ENTITY_DUPLICATE_TABLE"
FORGE_ENTITY_INVALID_INDEX = "FORGE_ENTITY_INVALID_INDEX"
FORGE_ENTITY_RESERVED_SQL_NAME = "FORGE_ENTITY_RESERVED_SQL_NAME"
FORGE_ENTITY_INVALID_SLUG_SOURCE = "FORGE_ENTITY_INVALID_SLUG_SOURCE"
FORGE_ENTITY_INVALID_DEFAULT = "FORGE_ENTITY_INVALID_DEFAULT"
FORGE_ENTITY_INVALID_COMPUTED = "FORGE_ENTITY_INVALID_COMPUTED"

# ── Erreurs de relation ───────────────────────────────────────────────────────

FORGE_RELATION_SCHEMA_INVALID = "FORGE_RELATION_SCHEMA_INVALID"
FORGE_RELATION_UNKNOWN_ENTITY = "FORGE_RELATION_UNKNOWN_ENTITY"
FORGE_RELATION_DUPLICATE = "FORGE_RELATION_DUPLICATE"
FORGE_RELATION_INVALID_ON_DELETE = "FORGE_RELATION_INVALID_ON_DELETE"
FORGE_RELATION_FK_COLLISION = "FORGE_RELATION_FK_COLLISION"

# ── Erreurs de table pivot ────────────────────────────────────────────────────

FORGE_PIVOT_SCHEMA_INVALID = "FORGE_PIVOT_SCHEMA_INVALID"
FORGE_PIVOT_TABLE_COLLISION = "FORGE_PIVOT_TABLE_COLLISION"
FORGE_PIVOT_RESERVED_FIELD = "FORGE_PIVOT_RESERVED_FIELD"
FORGE_PIVOT_KEY_COLLISION = "FORGE_PIVOT_KEY_COLLISION"
FORGE_PIVOT_UNIQUE_PAIR_REQUIRED = "FORGE_PIVOT_UNIQUE_PAIR_REQUIRED"

# ── Liste exhaustive (pour tests et documentation) ────────────────────────────

ALL_CODES: list[str] = [
    FORGE_ENTITY_JSON_INVALID,
    FORGE_ENTITY_SCHEMA_MISSING,
    FORGE_ENTITY_SCHEMA_INVALID,
    FORGE_ENTITY_DUPLICATE_FIELD,
    FORGE_ENTITY_RESERVED_PYTHON_NAME,
    FORGE_ENTITY_DUPLICATE_TABLE,
    FORGE_ENTITY_INVALID_INDEX,
    FORGE_ENTITY_RESERVED_SQL_NAME,
    FORGE_ENTITY_INVALID_SLUG_SOURCE,
    FORGE_ENTITY_INVALID_DEFAULT,
    FORGE_ENTITY_INVALID_COMPUTED,
    FORGE_RELATION_SCHEMA_INVALID,
    FORGE_RELATION_UNKNOWN_ENTITY,
    FORGE_RELATION_DUPLICATE,
    FORGE_RELATION_INVALID_ON_DELETE,
    FORGE_RELATION_FK_COLLISION,
    FORGE_PIVOT_SCHEMA_INVALID,
    FORGE_PIVOT_TABLE_COLLISION,
    FORGE_PIVOT_RESERVED_FIELD,
    FORGE_PIVOT_KEY_COLLISION,
    FORGE_PIVOT_UNIQUE_PAIR_REQUIRED,
]
